
VLOGAN	= vlogan
TOOL_HOME = /eda/synopsys/2019-20/RHELx86/VCS_2019.06-SP2/vcs/P-2019.06-SP2/linux64
DEP_CHECKER = $(TOOL_HOME)/bin/vfs

all :		vfs_check_depends_DEFAULT \



vfs_check_depends_DEFAULT :
	@$(DEP_CHECKER) checkdepends Makefile.Msimdepends.vlib_analyze_DEFAULT.dep ./re_analyze_vlib_DEFAULT
	@-if [ -f ./re_analyze_vlib_DEFAULT ]; then \
		chmod +x ./re_analyze_vlib_DEFAULT; \
		./re_analyze_vlib_DEFAULT; \
		\rm ./re_analyze_vlib_DEFAULT; \
	fi

